import { z } from "zod";
import {
  CERT_MODES,
  ENCRYPTION_MODES,
  ENCRYPTION_RTT,
  ENCRYPTION_TYPES,
  FLOWS,
  multiplexLevels,
  OMNIFLOW_AF_PATH_MODES,
  OMNIFLOW_CARRIERS,
  OMNIFLOW_FALLBACK_SCHEMES,
  OMNIFLOW_H3_FALLBACK_POLICIES,
  OMNIFLOW_PADDING_MODES,
  OMNIFLOW_SNI_MODES,
  OMNIFLOW_TLS_FINGERPRINTS,
  SECURITY,
  SIMNET_AF_MAGIC_MODES,
  SIMNET_AF_PATH_MODES,
  SIMNET_CARRIERS,
  SIMNET_FALLBACK_SCHEMES,
  SS_CIPHERS,
  TRANSPORTS,
  TUIC_CONGESTION,
  TUIC_UDP_RELAY_MODES,
  XHTTP_MODES,
} from "./constants";

const nullableString = z.string().nullish();
const nullableBool = z.boolean().nullish();
const nullablePort = z.number().int().min(0).max(65_535).nullish();
const nullableRatio = z.number().min(0).nullish();
const nullableNonNegativeInt = z.number().int().min(0).nullish();

const simnet = z.object({
  ratio: nullableRatio,
  type: z.literal("simnet"),
  enable: nullableBool,
  port: nullablePort,
  simnet_psk: nullableString,
  simnet_key_id: z.number().int().nullish(),
  simnet_ticket_id: nullableString,
  simnet_path: nullableString,
  simnet_carrier: z.enum(SIMNET_CARRIERS).nullish(),
  security: z.enum(["none", "tls"] as const).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  simnet_af_enabled: nullableBool,
  simnet_af_path_mode: z.enum(SIMNET_AF_PATH_MODES).nullish(),
  simnet_af_path_prefix: nullableString,
  simnet_af_path_suffix: nullableString,
  simnet_af_magic_mode: z.enum(SIMNET_AF_MAGIC_MODES).nullish(),
  simnet_af_response_jitter_ms: z.number().int().min(0).nullish(),
  simnet_af_handshake_polymorphism: nullableBool,
  simnet_af_settings_jitter: nullableBool,
  simnet_af_fake_header_injection: nullableBool,
  simnet_reverse_enabled: nullableBool,
  simnet_reverse_listen_addr: nullableString,
  simnet_reverse_listen_port: nullablePort,
  simnet_reverse_target_host: nullableString,
  simnet_reverse_target_port: nullablePort,
  simnet_fallback_enabled: nullableBool,
  simnet_fallback_target_scheme: z.enum(SIMNET_FALLBACK_SCHEMES).nullish(),
  simnet_fallback_target_host: nullableString,
  simnet_fallback_target_port: nullablePort,
  simnet_fallback_host_header: nullableString,
  simnet_fallback_tls_sni: nullableString,
  simnet_inbound_max_streams_per_session: nullableNonNegativeInt,
  simnet_inbound_max_udp_streams_per_session: nullableNonNegativeInt,
  simnet_inbound_max_handler_tasks_per_session: nullableNonNegativeInt,
  simnet_stream_event_channel_capacity: nullableNonNegativeInt,
  simnet_stream_data_channel_capacity: nullableNonNegativeInt,
  simnet_target_dial_timeout_ms: nullableNonNegativeInt,
  simnet_target_max_concurrent_dials: nullableNonNegativeInt,
  simnet_egress_block_loopback: nullableBool,
  simnet_egress_block_private: nullableBool,
  simnet_egress_block_link_local: nullableBool,
  simnet_egress_block_metadata: nullableBool,
  simnet_send_window: nullableNonNegativeInt,
  simnet_recv_window: nullableNonNegativeInt,
  simnet_max_concurrent_streams: nullableNonNegativeInt,
  simnet_initial_window_size: nullableNonNegativeInt,
  simnet_max_frame_size: nullableNonNegativeInt,
  simnet_client_max_concurrent_streams: nullableNonNegativeInt,
  simnet_client_max_streams_per_session: nullableNonNegativeInt,
  simnet_client_session_idle_timeout_secs: nullableNonNegativeInt,
  simnet_client_max_udp_sessions: nullableNonNegativeInt,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const ss = z.object({
  ratio: nullableRatio,
  type: z.literal("shadowsocks"),
  enable: nullableBool,
  port: nullablePort,
  cipher: z.enum(SS_CIPHERS).nullish(),
  server_key: nullableString,
  obfs: z.enum(["none", "http", "tls"] as const).nullish(),
  obfs_host: nullableString,
  obfs_path: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const vmess = z.object({
  ratio: nullableRatio,
  type: z.literal("vmess"),
  enable: nullableBool,
  host: nullableString,
  port: nullablePort,
  transport: z.enum(TRANSPORTS.vmess).nullish(),
  security: z.enum(SECURITY.vmess).nullish(),
  path: nullableString,
  service_name: nullableString,
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const vless = z.object({
  ratio: nullableRatio,
  type: z.literal("vless"),
  enable: nullableBool,
  host: nullableString,
  port: nullablePort,
  transport: z.enum(TRANSPORTS.vless).nullish(),
  security: z.enum(SECURITY.vless).nullish(),
  path: nullableString,
  service_name: nullableString,
  flow: z.enum(FLOWS.vless).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  reality_server_addr: nullableString,
  reality_server_port: nullablePort,
  reality_private_key: nullableString,
  reality_public_key: nullableString,
  reality_short_id: nullableString,
  xhttp_mode: z.enum(XHTTP_MODES).nullish(),
  xhttp_extra: nullableString,
  encryption: z.enum(ENCRYPTION_TYPES).nullish(),
  encryption_mode: z.enum(ENCRYPTION_MODES).nullish(),
  encryption_rtt: z.enum(ENCRYPTION_RTT).nullish(),
  encryption_ticket: nullableString,
  encryption_server_padding: nullableString,
  encryption_private_key: nullableString,
  encryption_client_padding: nullableString,
  encryption_password: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const trojan = z.object({
  ratio: nullableRatio,
  type: z.literal("trojan"),
  enable: nullableBool,
  host: nullableString,
  port: nullablePort,
  transport: z.enum(TRANSPORTS.trojan).nullish(),
  security: z.enum(SECURITY.trojan).nullish(),
  path: nullableString,
  service_name: nullableString,
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const hysteria = z.object({
  ratio: nullableRatio,
  type: z.literal("hysteria"),
  enable: nullableBool,
  hop_ports: nullableString,
  hop_interval: z.number().nullish(),
  obfs_password: nullableString,
  obfs: z.enum(["none", "salamander"] as const).nullish(),
  port: nullablePort,
  security: z.enum(SECURITY.hysteria).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
});

const tuic = z.object({
  ratio: nullableRatio,
  type: z.literal("tuic"),
  enable: nullableBool,
  host: nullableString,
  port: nullablePort,
  disable_sni: z.boolean().nullish(),
  reduce_rtt: z.boolean().nullish(),
  udp_relay_mode: z.enum(TUIC_UDP_RELAY_MODES).nullish(),
  congestion_controller: z.enum(TUIC_CONGESTION).nullish(),
  security: z.enum(SECURITY.tuic).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const anytls = z.object({
  ratio: nullableRatio,
  type: z.literal("anytls"),
  enable: nullableBool,
  port: nullablePort,
  security: z.enum(SECURITY.anytls).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  padding_scheme: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const mx = z.object({
  ratio: nullableRatio,
  type: z.literal("mx"),
  enable: nullableBool,
  host: nullableString,
  port: nullablePort,
  transport: z.enum(TRANSPORTS.mx).nullish(),
  security: z.enum(SECURITY.mx).nullish(),
  path: nullableString,
  service_name: nullableString,
  mc1_mode: nullableString,
  mc1_cidr_segments: z.union([z.array(z.string()), z.string()]).nullish(),
  mundo_username: nullableString,
  mundo_certificate_fingerprint: nullableString,
  mundo_fake_title: nullableString,
  mundo_fake_message: nullableString,
  mundo_accept_proxy_protocol: nullableBool,
  mundo_use_tls_certificate: nullableBool,
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  reality_server_addr: nullableString,
  reality_server_port: nullablePort,
  reality_private_key: nullableString,
  reality_public_key: nullableString,
  reality_short_id: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const socks = z.object({
  ratio: nullableRatio,
  type: z.literal("socks"),
  enable: nullableBool,
  port: nullablePort,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const naive = z.object({
  ratio: nullableRatio,
  type: z.literal("naive"),
  enable: nullableBool,
  port: nullablePort,
  security: z.enum(SECURITY.naive).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const http = z.object({
  ratio: nullableRatio,
  type: z.literal("http"),
  enable: nullableBool,
  port: nullablePort,
  security: z.enum(SECURITY.http).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  fingerprint: nullableString,
  cert_mode: z.enum(CERT_MODES).nullish(),
  cert_dns_provider: nullableString,
  cert_dns_env: nullableString,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const mieru = z.object({
  ratio: nullableRatio,
  type: z.literal("mieru"),
  enable: nullableBool,
  port: nullablePort,
  multiplex: z.enum(multiplexLevels).nullish(),
  transport: z.enum(TRANSPORTS.mieru).nullish(),
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

const omniflow = z.object({
  ratio: nullableRatio,
  type: z.literal("omniflow"),
  enable: nullableBool,
  port: nullablePort,
  security: z.enum(["tls"] as const).nullish(),
  sni: nullableString,
  allow_insecure: nullableBool,
  omniflow_carrier: z.enum(OMNIFLOW_CARRIERS).nullish(),
  omniflow_path: nullableString,
  omniflow_content_type: nullableString,
  omniflow_profile_path: nullableString,
  omniflow_profile_json: nullableString,
  omniflow_server_host: nullableString,
  omniflow_server_port: z.number().int().min(1).max(65_535).nullish(),
  omniflow_ca_cert_path: nullableString,
  omniflow_target_meta: nullableString,
  omniflow_spki_pin: nullableString,
  omniflow_h3_fallback_enabled: nullableBool,
  omniflow_h3_fallback_policy: z.enum(OMNIFLOW_H3_FALLBACK_POLICIES).nullish(),
  omniflow_h3_fallback_timeout_ms: z
    .number()
    .int()
    .min(100)
    .max(30_000)
    .nullish(),
  omniflow_h3_fallback_retry_budget: z.number().int().min(0).max(100).nullish(),
  omniflow_h3_fallback_smoke_enabled: nullableBool,
  omniflow_h3_fallback_smoke_interval_sec: z.number().int().min(1).nullish(),
  omniflow_h3_fallback_smoke_timeout_ms: z.number().int().min(100).nullish(),
  omniflow_max_age_sec: z.number().int().min(0).nullish(),
  omniflow_idle_timeout_sec: z.number().int().min(0).nullish(),
  omniflow_max_connections: z.number().int().min(1).max(1000).nullish(),
  omniflow_adaptive_tls_enabled: nullableBool,
  omniflow_tls_fingerprint: z.enum(OMNIFLOW_TLS_FINGERPRINTS).nullish(),
  omniflow_sni_mode: z.enum(OMNIFLOW_SNI_MODES).nullish(),
  omniflow_padding_mode: z.enum(OMNIFLOW_PADDING_MODES).nullish(),
  omniflow_traffic_shaping_enabled: nullableBool,
  omniflow_af_enabled: nullableBool,
  omniflow_af_path_mode: z.enum(OMNIFLOW_AF_PATH_MODES).nullish(),
  omniflow_af_path_prefix: nullableString,
  omniflow_af_path_suffix: nullableString,
  omniflow_af_path_rotation_secs: z.number().int().min(1).nullish(),
  omniflow_af_path_skew_slots: z.number().int().min(0).nullish(),
  omniflow_fallback_enabled: nullableBool,
  omniflow_fallback_target_scheme: z.enum(OMNIFLOW_FALLBACK_SCHEMES).nullish(),
  omniflow_fallback_target_host: nullableString,
  omniflow_fallback_target_port: nullablePort,
  omniflow_fallback_host_header: nullableString,
  omniflow_fallback_tls_sni: nullableString,
  omniflow_fallback_carrier_enabled: nullableBool,
  omniflow_fallback_connect_tunnel: nullableBool,
  omniflow_fallback_wss_enabled: nullableBool,
  up_mbps: z.number().nullish(),
  down_mbps: z.number().nullish(),
});

export const protocolApiScheme = z.discriminatedUnion("type", [
  simnet,
  omniflow,
  ss,
  vmess,
  vless,
  trojan,
  mx,
  hysteria,
  tuic,
  anytls,
  socks,
  naive,
  http,
  mieru,
]);

export const formSchema = z.object({
  name: z.string().min(1),
  address: z.string().min(1),
  country: z.string().optional(),
  city: z.string().optional(),
  protocols: z.array(protocolApiScheme),
});
