import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import {
  generateMLKEM768KeyPair,
  generatePassword,
  generateRealityKeyPair,
  generateRealityShortId,
} from "../generate";
import {
  CERT_MODES,
  ENCRYPTION_MODES,
  ENCRYPTION_RTT,
  ENCRYPTION_TYPES,
  FINGERPRINTS,
  FLOWS,
  multiplexLevels,
  OMNIFLOW_AF_PATH_MODES,
  OMNIFLOW_CARRIERS,
  OMNIFLOW_FALLBACK_SCHEMES,
  OMNIFLOW_H3_FALLBACK_POLICIES,
  OMNIFLOW_PADDING_MODES,
  OMNIFLOW_SNI_MODES,
  OMNIFLOW_TLS_FINGERPRINTS,
  SECURITY,
  SIMNET_AF_MAGIC_MODES,
  SIMNET_AF_PATH_MODES,
  SIMNET_CARRIERS,
  SIMNET_FALLBACK_SCHEMES,
  SS_CIPHERS,
  TRANSPORTS,
  TUIC_CONGESTION,
  TUIC_UDP_RELAY_MODES,
  XHTTP_MODES,
} from "./constants";
import type { FieldConfig } from "./types";

export function useProtocolFields() {
  const { t } = useTranslation("servers");

  return useMemo<Record<string, FieldConfig[]>>(
    () => ({
      simnet: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "443",
          group: "basic",
        },
        {
          name: "simnet_psk",
          type: "input",
          label: t("simnet_psk", "SimNet PSK"),
          placeholder: t(
            "simnet_psk_placeholder",
            "Server pre-shared key (shared across all users)"
          ),
          generate: {
            function: () => generatePassword(32),
          },
          group: "basic",
        },
        {
          name: "simnet_ticket_id",
          type: "input",
          label: t("simnet_ticket_id", "SimNet Ticket ID"),
          placeholder: t("simnet_ticket_id_placeholder", "Optional ticket id"),
          group: "basic",
        },
        {
          name: "simnet_path",
          type: "input",
          label: t("simnet_path", "SimNet Path"),
          placeholder: t("simnet_path_placeholder", "e.g. /simnet"),
          group: "basic",
        },
        {
          name: "simnet_carrier",
          type: "select",
          label: t("simnet_carrier", "Carrier"),
          options: SIMNET_CARRIERS,
          defaultValue: "h2",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "security",
          type: "select",
          label: t("security", "Security"),
          options: ["none", "tls"],
          defaultValue: "tls",
          group: "security",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          placeholder: t("sni_placeholder", "e.g. edge.example.com"),
          group: "security",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
        {
          name: "simnet_af_enabled",
          type: "switch",
          label: t("simnet_af_enabled", "Enable Anti-Fingerprint"),
          group: "simnet",
        },
        {
          name: "simnet_af_path_mode",
          type: "select",
          label: t("simnet_af_path_mode", "AF Path Mode"),
          options: SIMNET_AF_PATH_MODES,
          defaultValue: "api",
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_af_path_prefix",
          type: "input",
          label: t("simnet_af_path_prefix", "AF Path Prefix"),
          placeholder: t(
            "simnet_af_path_prefix_placeholder",
            "Optional path prefix"
          ),
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_af_path_suffix",
          type: "input",
          label: t("simnet_af_path_suffix", "AF Path Suffix"),
          placeholder: t(
            "simnet_af_path_suffix_placeholder",
            "Optional path suffix"
          ),
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_af_magic_mode",
          type: "select",
          label: t("simnet_af_magic_mode", "AF Magic Mode"),
          options: SIMNET_AF_MAGIC_MODES,
          defaultValue: "derived",
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_af_response_jitter_ms",
          type: "number",
          label: t("simnet_af_response_jitter_ms", "AF Response Jitter"),
          min: 0,
          suffix: "ms",
          defaultValue: 50,
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_af_handshake_polymorphism",
          type: "switch",
          label: t(
            "simnet_af_handshake_polymorphism",
            "Handshake Polymorphism"
          ),
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_af_settings_jitter",
          type: "switch",
          label: t("simnet_af_settings_jitter", "Settings Jitter"),
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_af_fake_header_injection",
          type: "switch",
          label: t("simnet_af_fake_header_injection", "Fake Header Injection"),
          group: "simnet",
          condition: (p) => !!p.simnet_af_enabled,
        },
        {
          name: "simnet_reverse_enabled",
          type: "switch",
          label: t("simnet_reverse_enabled", "Enable Local Reverse Proxy"),
          group: "simnet",
        },
        {
          name: "simnet_reverse_listen_addr",
          type: "input",
          label: t("simnet_reverse_listen_addr", "Reverse Listen Address"),
          placeholder: "127.0.0.1",
          group: "simnet",
          condition: (p) => !!p.simnet_reverse_enabled,
        },
        {
          name: "simnet_reverse_listen_port",
          type: "number",
          label: t("simnet_reverse_listen_port", "Reverse Listen Port"),
          min: 1,
          max: 65_535,
          placeholder: "18080",
          group: "simnet",
          condition: (p) => !!p.simnet_reverse_enabled,
        },
        {
          name: "simnet_reverse_target_host",
          type: "input",
          label: t("simnet_reverse_target_host", "Reverse Target Host"),
          placeholder: "127.0.0.1",
          group: "simnet",
          condition: (p) => !!p.simnet_reverse_enabled,
        },
        {
          name: "simnet_reverse_target_port",
          type: "number",
          label: t("simnet_reverse_target_port", "Reverse Target Port"),
          min: 1,
          max: 65_535,
          placeholder: "8080",
          group: "simnet",
          condition: (p) => !!p.simnet_reverse_enabled,
        },
        {
          name: "simnet_fallback_enabled",
          type: "switch",
          label: t(
            "simnet_fallback_enabled",
            "Enable HTTPS Fallback Reverse Proxy"
          ),
          group: "simnet",
        },
        {
          name: "simnet_fallback_target_scheme",
          type: "select",
          label: t("simnet_fallback_target_scheme", "Fallback Target Scheme"),
          options: SIMNET_FALLBACK_SCHEMES,
          defaultValue: "https",
          group: "simnet",
          condition: (p) => !!p.simnet_fallback_enabled,
        },
        {
          name: "simnet_fallback_target_host",
          type: "input",
          label: t("simnet_fallback_target_host", "Fallback Target Host"),
          placeholder: t(
            "simnet_fallback_target_host_placeholder",
            "e.g. www.example.com"
          ),
          group: "simnet",
          condition: (p) => !!p.simnet_fallback_enabled,
        },
        {
          name: "simnet_fallback_target_port",
          type: "number",
          label: t("simnet_fallback_target_port", "Fallback Target Port"),
          min: 1,
          max: 65_535,
          placeholder: "443 / 80",
          group: "simnet",
          condition: (p) => !!p.simnet_fallback_enabled,
        },
        {
          name: "simnet_fallback_host_header",
          type: "input",
          label: t("simnet_fallback_host_header", "Fallback Host Header"),
          placeholder: t(
            "simnet_fallback_host_header_placeholder",
            "Optional, defaults to target host"
          ),
          group: "simnet",
          condition: (p) => !!p.simnet_fallback_enabled,
        },
        {
          name: "simnet_fallback_tls_sni",
          type: "input",
          label: t("simnet_fallback_tls_sni", "Fallback TLS SNI"),
          placeholder: t(
            "simnet_fallback_tls_sni_placeholder",
            "Optional, defaults to target host"
          ),
          group: "simnet",
          condition: (p) => !!p.simnet_fallback_enabled,
        },
      ],
      omniflow: [
        // Group 1: basic
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "443",
          group: "basic",
        },
        {
          name: "omniflow_carrier",
          type: "select",
          label: t("omniflow_carrier", "Carrier Transport"),
          options: OMNIFLOW_CARRIERS,
          defaultValue: "h2",
          group: "basic",
        },
        {
          name: "omniflow_path",
          type: "input",
          label: t("omniflow_path", "HTTP Path"),
          placeholder: t("omniflow_path_placeholder", "e.g. /omniflow"),
          group: "basic",
        },
        {
          name: "omniflow_content_type",
          type: "input",
          label: t("omniflow_content_type", "Content Type"),
          placeholder: t(
            "omniflow_content_type_placeholder",
            "e.g. application/grpc"
          ),
          group: "basic",
        },
        {
          name: "omniflow_server_host",
          type: "input",
          label: t("omniflow_server_host", "Server Host"),
          placeholder: t(
            "omniflow_server_host_placeholder",
            "e.g. example.com"
          ),
          group: "basic",
        },
        {
          name: "omniflow_server_port",
          type: "number",
          label: t("omniflow_server_port", "Server Port"),
          min: 1,
          max: 65_535,
          placeholder: t("omniflow_server_port_placeholder", "e.g. 443"),
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        // Group 2: security
        {
          name: "security",
          type: "select",
          label: t("security", "Security"),
          options: ["tls"],
          defaultValue: "tls",
          group: "security",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          placeholder: t("sni_placeholder", "e.g. edge.example.com"),
          group: "security",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
        },
        {
          name: "omniflow_ca_cert_path",
          type: "input",
          label: t("omniflow_ca_cert_path", "CA Certificate Path"),
          placeholder: t(
            "omniflow_ca_cert_path_placeholder",
            "Path to CA certificate file"
          ),
          group: "security",
        },
        {
          name: "omniflow_spki_pin",
          type: "input",
          label: t("omniflow_spki_pin", "SPKI Pin"),
          placeholder: t(
            "omniflow_spki_pin_placeholder",
            "Subject Public Key Info pin"
          ),
          group: "security",
        },
        {
          name: "omniflow_sni_mode",
          type: "select",
          label: t("omniflow_sni_mode", "SNI Mode"),
          options: OMNIFLOW_SNI_MODES,
          group: "security",
        },
        // Group 3: omniflow (OmniFlow Profile)
        {
          name: "omniflow_profile_path",
          type: "input",
          label: t("omniflow_profile_path", "Profile File Path"),
          placeholder: t(
            "omniflow_profile_path_placeholder",
            "Path to profile file on server"
          ),
          group: "omniflow",
        },
        {
          name: "omniflow_profile_json",
          type: "textarea",
          label: t("omniflow_profile_json", "Profile JSON"),
          placeholder: t(
            "omniflow_profile_json_placeholder",
            "Inline profile JSON configuration"
          ),
          group: "omniflow",
        },
        {
          name: "omniflow_target_meta",
          type: "input",
          label: t("omniflow_target_meta", "Encrypted Target Meta"),
          placeholder: t(
            "omniflow_target_meta_placeholder",
            "Encrypted target metadata"
          ),
          group: "omniflow",
        },
        // Group 4: omniflow (H3 Fallback)
        {
          name: "omniflow_h3_fallback_enabled",
          type: "switch",
          label: t("omniflow_h3_fallback_enabled", "Enable H3 Fallback"),
          group: "omniflow",
          condition: (p) =>
            p.omniflow_carrier === "h3" || !!p.omniflow_h3_fallback_enabled,
        },
        {
          name: "omniflow_h3_fallback_policy",
          type: "select",
          label: t("omniflow_h3_fallback_policy", "H3 Fallback Policy"),
          options: OMNIFLOW_H3_FALLBACK_POLICIES,
          group: "omniflow",
          condition: (p) =>
            p.omniflow_carrier === "h3" || !!p.omniflow_h3_fallback_enabled,
        },
        {
          name: "omniflow_h3_fallback_timeout_ms",
          type: "number",
          label: t(
            "omniflow_h3_fallback_timeout_ms",
            "H3 Fallback Timeout (ms)"
          ),
          min: 100,
          max: 30_000,
          step: 100,
          group: "omniflow",
          condition: (p) =>
            p.omniflow_carrier === "h3" || !!p.omniflow_h3_fallback_enabled,
        },
        {
          name: "omniflow_h3_fallback_retry_budget",
          type: "number",
          label: t(
            "omniflow_h3_fallback_retry_budget",
            "H3 Fallback Retry Budget"
          ),
          min: 0,
          max: 100,
          group: "omniflow",
          condition: (p) =>
            p.omniflow_carrier === "h3" || !!p.omniflow_h3_fallback_enabled,
        },
        {
          name: "omniflow_h3_fallback_smoke_enabled",
          type: "switch",
          label: t("omniflow_h3_fallback_smoke_enabled", "Enable Smoke Test"),
          group: "omniflow",
          condition: (p) =>
            p.omniflow_carrier === "h3" || !!p.omniflow_h3_fallback_enabled,
        },
        {
          name: "omniflow_h3_fallback_smoke_interval_sec",
          type: "number",
          label: t(
            "omniflow_h3_fallback_smoke_interval_sec",
            "Smoke Test Interval (sec)"
          ),
          min: 1,
          group: "omniflow",
          condition: (p) =>
            p.omniflow_carrier === "h3" || !!p.omniflow_h3_fallback_enabled,
        },
        {
          name: "omniflow_h3_fallback_smoke_timeout_ms",
          type: "number",
          label: t(
            "omniflow_h3_fallback_smoke_timeout_ms",
            "Smoke Test Timeout (ms)"
          ),
          min: 100,
          group: "omniflow",
          condition: (p) =>
            p.omniflow_carrier === "h3" || !!p.omniflow_h3_fallback_enabled,
        },
        // Group 5: omniflow (Connection Management)
        {
          name: "omniflow_max_age_sec",
          type: "number",
          label: t("omniflow_max_age_sec", "Max Connection Age (sec)"),
          min: 0,
          placeholder: t("omniflow_max_age_sec_placeholder", "0 for unlimited"),
          group: "omniflow",
        },
        {
          name: "omniflow_idle_timeout_sec",
          type: "number",
          label: t("omniflow_idle_timeout_sec", "Idle Timeout (sec)"),
          min: 0,
          placeholder: t("omniflow_idle_timeout_sec_placeholder", "e.g. 300"),
          group: "omniflow",
        },
        {
          name: "omniflow_max_connections",
          type: "number",
          label: t("omniflow_max_connections", "Max Connections"),
          min: 1,
          max: 1000,
          placeholder: t("omniflow_max_connections_placeholder", "e.g. 8"),
          group: "omniflow",
        },
        // Group 6: omniflow (Anti-Fingerprint)
        {
          name: "omniflow_adaptive_tls_enabled",
          type: "switch",
          label: t("omniflow_adaptive_tls_enabled", "Enable Adaptive TLS"),
          group: "omniflow",
        },
        {
          name: "omniflow_tls_fingerprint",
          type: "select",
          label: t("omniflow_tls_fingerprint", "TLS Fingerprint"),
          options: OMNIFLOW_TLS_FINGERPRINTS,
          group: "omniflow",
        },
        {
          name: "omniflow_padding_mode",
          type: "select",
          label: t("omniflow_padding_mode", "Padding Mode"),
          options: OMNIFLOW_PADDING_MODES,
          group: "omniflow",
        },
        {
          name: "omniflow_traffic_shaping_enabled",
          type: "switch",
          label: t(
            "omniflow_traffic_shaping_enabled",
            "Enable Traffic Shaping"
          ),
          group: "omniflow",
        },
        {
          name: "omniflow_af_enabled",
          type: "switch",
          label: t("omniflow_af_enabled", "Enable Random AF Path"),
          group: "omniflow",
        },
        {
          name: "omniflow_af_path_mode",
          type: "select",
          label: t("omniflow_af_path_mode", "AF Path Mode"),
          options: OMNIFLOW_AF_PATH_MODES,
          group: "omniflow",
          condition: (p) => !!p.omniflow_af_enabled,
        },
        {
          name: "omniflow_af_path_prefix",
          type: "input",
          label: t("omniflow_af_path_prefix", "AF Path Prefix"),
          placeholder: t("omniflow_af_path_prefix_placeholder", "e.g. /api/v2"),
          group: "omniflow",
          condition: (p) => !!p.omniflow_af_enabled,
        },
        {
          name: "omniflow_af_path_suffix",
          type: "input",
          label: t("omniflow_af_path_suffix", "AF Path Suffix"),
          placeholder: t("omniflow_af_path_suffix_placeholder", "e.g. .woff2"),
          group: "omniflow",
          condition: (p) => !!p.omniflow_af_enabled,
        },
        {
          name: "omniflow_af_path_rotation_secs",
          type: "number",
          label: t("omniflow_af_path_rotation_secs", "AF Path Rotation (sec)"),
          min: 1,
          placeholder: t("omniflow_af_path_rotation_secs_placeholder", "300"),
          group: "omniflow",
          condition: (p) => !!p.omniflow_af_enabled,
        },
        {
          name: "omniflow_af_path_skew_slots",
          type: "number",
          label: t("omniflow_af_path_skew_slots", "AF Path Skew Slots"),
          min: 0,
          placeholder: t("omniflow_af_path_skew_slots_placeholder", "1"),
          group: "omniflow",
          condition: (p) => !!p.omniflow_af_enabled,
        },
        // Group 7: omniflow (Browser Fallback Reverse Proxy)
        {
          name: "omniflow_fallback_enabled",
          type: "switch",
          label: t(
            "omniflow_fallback_enabled",
            "Enable HTTPS Fallback Reverse Proxy"
          ),
          group: "omniflow",
        },
        {
          name: "omniflow_fallback_target_scheme",
          type: "select",
          label: t("omniflow_fallback_target_scheme", "Fallback Target Scheme"),
          options: OMNIFLOW_FALLBACK_SCHEMES,
          defaultValue: "https",
          group: "omniflow",
          condition: (p) => !!p.omniflow_fallback_enabled,
        },
        {
          name: "omniflow_fallback_target_host",
          type: "input",
          label: t("omniflow_fallback_target_host", "Fallback Target Host"),
          placeholder: t(
            "omniflow_fallback_target_host_placeholder",
            "e.g. www.example.com"
          ),
          group: "omniflow",
          condition: (p) => !!p.omniflow_fallback_enabled,
        },
        {
          name: "omniflow_fallback_target_port",
          type: "number",
          label: t("omniflow_fallback_target_port", "Fallback Target Port"),
          min: 1,
          max: 65_535,
          placeholder: "443 / 80",
          group: "omniflow",
          condition: (p) => !!p.omniflow_fallback_enabled,
        },
        {
          name: "omniflow_fallback_host_header",
          type: "input",
          label: t("omniflow_fallback_host_header", "Fallback Host Header"),
          placeholder: t(
            "omniflow_fallback_host_header_placeholder",
            "Optional, defaults to target host"
          ),
          group: "omniflow",
          condition: (p) => !!p.omniflow_fallback_enabled,
        },
        {
          name: "omniflow_fallback_tls_sni",
          type: "input",
          label: t("omniflow_fallback_tls_sni", "Fallback TLS SNI"),
          placeholder: t(
            "omniflow_fallback_tls_sni_placeholder",
            "Optional, defaults to target host"
          ),
          group: "omniflow",
          condition: (p) => !!p.omniflow_fallback_enabled,
        },
        // Group 8: omniflow (Fallback Carrier)
        {
          name: "omniflow_fallback_carrier_enabled",
          type: "switch",
          label: t(
            "omniflow_fallback_carrier_enabled",
            "Enable Fallback Carrier"
          ),
          group: "omniflow",
        },
        {
          name: "omniflow_fallback_connect_tunnel",
          type: "switch",
          label: t(
            "omniflow_fallback_connect_tunnel",
            "HTTP/1.1 CONNECT Tunnel"
          ),
          group: "omniflow",
        },
        {
          name: "omniflow_fallback_wss_enabled",
          type: "switch",
          label: t("omniflow_fallback_wss_enabled", "WSS Fallback"),
          group: "omniflow",
        },
      ],
      shadowsocks: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "cipher",
          type: "select",
          label: t("cipher", "Encryption Algorithm"),
          options: SS_CIPHERS,
          defaultValue: "chacha20-ietf-poly1305",
          group: "basic",
        },
        {
          name: "server_key",
          type: "input",
          label: t("server_key", "Server Key"),
          generate: {
            function: () => generatePassword(32),
          },
          group: "basic",
          condition: (p) =>
            [
              "2022-blake3-aes-128-gcm",
              "2022-blake3-aes-256-gcm",
              "2022-blake3-chacha20-poly1305",
            ].includes(p.cipher),
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "obfs",
          type: "select",
          label: t("obfs", "Obfuscation"),
          options: ["none", "http", "tls"],
          defaultValue: "none",
          group: "obfs",
        },
        {
          name: "obfs_host",
          type: "input",
          label: t("host", "Host"),
          placeholder: "e.g. www.bing.com",
          group: "obfs",
          condition: (p) => p.obfs && p.obfs !== "none",
        },
        {
          name: "obfs_path",
          type: "input",
          label: t("path", "Path"),
          placeholder: "e.g. /path/to/obfs",
          group: "obfs",
          condition: (p) => p.obfs && p.obfs !== "none",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
          condition: (p) => p.obfs === "tls",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
          condition: (p) => p.obfs === "tls",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
          condition: (p) => p.obfs === "tls",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.obfs === "tls" && p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.obfs === "tls" && p.cert_mode === "dns",
        },
      ],
      vmess: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "transport",
          type: "select",
          label: t("transport", "Transport"),
          options: TRANSPORTS.vmess,
          defaultValue: "tcp",
          group: "transport",
        },
        {
          name: "security",
          type: "select",
          label: t("security", "Security"),
          options: SECURITY.vmess,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "host",
          type: "input",
          label: t("host", "Host"),
          placeholder: "e.g. www.bing.com",
          group: "transport",
          condition: (p) =>
            ["websocket", "xhttp", "httpupgrade"].includes(p.transport),
        },
        {
          name: "path",
          type: "input",
          label: t("path", "Path"),
          placeholder: "e.g. /path/to/obfs",
          group: "transport",
          condition: (p) =>
            ["websocket", "xhttp", "httpupgrade"].includes(p.transport),
        },
        {
          name: "service_name",
          type: "input",
          label: t("service_name", "Service Name"),
          group: "transport",
          condition: (p) => p.transport === "grpc",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
          condition: (p) => p.security === "tls",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
      ],
      vless: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "transport",
          type: "select",
          label: t("transport", "Transport"),
          options: TRANSPORTS.vless,
          defaultValue: "tcp",
          group: "transport",
        },
        {
          name: "flow",
          type: "select",
          label: t("flow", "Flow"),
          options: FLOWS.vless,
          defaultValue: "none",
          group: "transport",
          condition: (p) => p.transport === "tcp",
        },
        {
          name: "security",
          type: "select",
          label: t("security", "Security"),
          options: SECURITY.vless,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "host",
          type: "input",
          label: t("host", "Host"),
          placeholder: "e.g. www.bing.com",
          group: "transport",
          condition: (p) =>
            ["websocket", "mkcp", "httpupgrade", "xhttp"].includes(p.transport),
        },
        {
          name: "path",
          type: "input",
          label: t("path", "Path"),
          placeholder: "e.g. /path/to/obfs",
          group: "transport",
          condition: (p) =>
            ["websocket", "mkcp", "httpupgrade", "xhttp"].includes(p.transport),
        },
        {
          name: "service_name",
          type: "input",
          label: t("service_name", "Service Name"),
          group: "transport",
          condition: (p) => p.transport === "grpc",
        },
        {
          name: "xhttp_mode",
          type: "select",
          label: t("mode", "Mode"),
          options: XHTTP_MODES,
          defaultValue: "auto",
          group: "transport",
          condition: (p) => p.transport === "xhttp",
        },
        {
          name: "xhttp_extra",
          type: "textarea",
          label: t("extra", "Extra"),
          placeholder: "{}",
          group: "transport",
          condition: (p) => p.transport === "xhttp",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "reality_server_addr",
          type: "input",
          label: t("security_server_address", "Reality Server Address"),
          placeholder: t(
            "security_server_address_placeholder",
            "e.g. 1.2.3.4 or domain"
          ),
          group: "reality",
          condition: (p) => p.security === "reality",
        },
        {
          name: "reality_server_port",
          type: "number",
          label: t("security_server_port", "Reality Server Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "reality",
          condition: (p) => p.security === "reality",
        },
        {
          name: "reality_private_key",
          type: "input",
          label: t("security_private_key", "Reality Private Key"),
          placeholder: t(
            "security_private_key_placeholder",
            "Enter private key"
          ),
          group: "reality",
          generate: {
            function: generateRealityKeyPair,
            updateFields: {
              reality_private_key: "privateKey",
              reality_public_key: "publicKey",
            } as Record<string, string>,
          },
          condition: (p) => p.security === "reality",
        },
        {
          name: "reality_public_key",
          type: "input",
          label: t("security_public_key", "Reality Public Key"),
          placeholder: t("security_public_key_placeholder", "Enter public key"),
          group: "reality",
          condition: (p) => p.security === "reality",
        },
        {
          name: "reality_short_id",
          type: "input",
          label: t("security_short_id", "Reality Short ID"),
          group: "reality",
          generate: {
            function: generateRealityShortId,
          },
          condition: (p) => p.security === "reality",
        },
        {
          name: "encryption",
          type: "select",
          label: t("encryption", "Encryption"),
          options: ENCRYPTION_TYPES,
          defaultValue: "none",
          group: "encryption",
        },
        {
          name: "encryption_mode",
          type: "select",
          label: t("encryption_mode", "Mode"),
          options: ENCRYPTION_MODES,
          defaultValue: "native",
          group: "encryption",
          condition: (p) => p.encryption === "mlkem768x25519plus",
        },
        {
          name: "encryption_rtt",
          type: "select",
          label: t("encryption_rtt", "RTT"),
          options: ENCRYPTION_RTT,
          defaultValue: "1rtt",
          group: "encryption",
          condition: (p) => p.encryption === "mlkem768x25519plus",
        },
        {
          name: "encryption_ticket",
          type: "input",
          label: t("encryption_ticket", "Ticket Time"),
          placeholder: "e.g. 600s",
          group: "encryption",
          condition: (p) =>
            p.encryption === "mlkem768x25519plus" &&
            p.encryption_rtt === "0rtt",
        },
        {
          name: "encryption_server_padding",
          type: "input",
          label: t("encryption_server_padding", "Server Padding"),
          placeholder: "e.g. 100-111-1111.75-0-111.50-0-3333",
          group: "encryption",
          condition: (p) => p.encryption === "mlkem768x25519plus",
        },
        {
          name: "encryption_private_key",
          type: "input",
          label: t("encryption_private_key", "Private Key"),
          placeholder: t(
            "encryption_private_key_placeholder",
            "Leave empty for auto-generation"
          ),
          group: "encryption",
          generate: {
            functions: [
              {
                label: t(
                  "generate_standard_encryption_key",
                  "Generate Standard Key"
                ),
                function: generateRealityKeyPair,
              },
              {
                label: t(
                  "generate_quantum_resistant_key",
                  "Generate Quantum-Resistant Key"
                ),
                function: generateMLKEM768KeyPair,
              },
            ],
            updateFields: {
              encryption_private_key: "privateKey",
              encryption_password: "publicKey",
            } as Record<string, string>,
          },
          condition: (p) => p.encryption === "mlkem768x25519plus",
        },
        {
          name: "encryption_client_padding",
          type: "input",
          label: t("encryption_client_padding", "Client Padding"),
          placeholder: "e.g. 100-111-1111.75-0-111.50-0-3333",
          group: "encryption",
          condition: (p) => p.encryption === "mlkem768x25519plus",
        },
        {
          name: "encryption_password",
          type: "input",
          label: t("encryption_password", "Password"),
          placeholder: t(
            "encryption_password_placeholder",
            "Leave empty for auto-generation"
          ),
          group: "encryption",
          condition: (p) => p.encryption === "mlkem768x25519plus",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
          condition: (p) => p.security === "tls",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
      ],
      trojan: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "transport",
          type: "select",
          label: t("transport", "Transport"),
          options: TRANSPORTS.trojan,
          defaultValue: "tcp",
          group: "transport",
        },
        {
          name: "security",
          type: "select",
          label: t("security", "Security"),
          options: SECURITY.trojan,
          defaultValue: "tls",
          group: "security",
        },
        {
          name: "host",
          type: "input",
          label: t("host", "Host"),
          placeholder: "e.g. www.bing.com",
          group: "transport",
          condition: (p) =>
            ["websocket", "xhttp", "httpupgrade"].includes(p.transport),
        },
        {
          name: "path",
          type: "input",
          label: t("path", "Path"),
          placeholder: "e.g. /path/to/obfs",
          group: "transport",
          condition: (p) =>
            ["websocket", "xhttp", "httpupgrade"].includes(p.transport),
        },
        {
          name: "service_name",
          type: "input",
          label: t("service_name", "Service Name"),
          group: "transport",
          condition: (p) => p.transport === "grpc",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
          condition: (p) => p.security === "tls",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
      ],
      hysteria: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "hop_ports",
          type: "input",
          label: t("hop_ports", "Hop Ports"),
          placeholder: t("hop_ports_placeholder", "e.g. 1-65535"),
          group: "basic",
        },
        {
          name: "hop_interval",
          type: "number",
          label: t("hop_interval", "Hop Interval"),
          placeholder: "e.g. 300",
          min: 1,
          suffix: "S",
          group: "basic",
        },
        {
          name: "obfs",
          type: "select",
          label: t("obfs", "Obfuscation"),
          options: ["none", "salamander"],
          defaultValue: "none",
          group: "obfs",
        },
        {
          name: "obfs_password",
          type: "input",
          label: t("obfs_password", "Obfuscation Password"),
          placeholder: t(
            "obfs_password_placeholder",
            "Enter obfuscation password"
          ),
          generate: {
            function: () => generatePassword(16),
          },
          group: "obfs",
          condition: (p) => p.obfs && p.obfs !== "none",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
      ],
      tuic: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "udp_relay_mode",
          type: "select",
          label: t("udp_relay_mode", "UDP Relay Mode"),
          options: TUIC_UDP_RELAY_MODES,
          defaultValue: "native",
          group: "basic",
        },
        {
          name: "congestion_controller",
          type: "select",
          label: t("congestion_controller", "Congestion Controller"),
          options: TUIC_CONGESTION,
          defaultValue: "bbr",
          group: "basic",
        },
        {
          name: "disable_sni",
          type: "switch",
          label: t("disable_sni", "Disable SNI"),
          group: "basic",
        },
        {
          name: "reduce_rtt",
          type: "switch",
          label: t("reduce_rtt", "Reduce RTT"),
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
      ],
      socks: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
      ],
      naive: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "security",
          type: "select",
          label: t("security", "Security"),
          options: SECURITY.naive,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
          condition: (p) => p.security === "tls",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
      ],
      http: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "security",
          type: "select",
          label: t("security", "Security"),
          options: SECURITY.http,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
          condition: (p) => p.security !== "none",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
          condition: (p) => p.security === "tls",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.security === "tls" && p.cert_mode === "dns",
        },
      ],
      mieru: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "multiplex",
          type: "select",
          label: t("multiplex", "Multiplex"),
          options: multiplexLevels,
          defaultValue: "off",
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "transport",
          type: "select",
          label: t("transport", "Transport"),
          options: TRANSPORTS.mieru,
          defaultValue: "tcp",
          group: "transport",
        },
      ],
      anytls: [
        {
          name: "ratio",
          type: "number",
          label: t("traffic_ratio", "Ratio"),
          min: 0,
          step: 0.01,
          defaultValue: 1,
          group: "basic",
        },
        {
          name: "port",
          type: "number",
          label: t("port", "Port"),
          min: 1,
          max: 65_535,
          placeholder: "1-65535",
          group: "basic",
        },
        {
          name: "padding_scheme",
          type: "textarea",
          label: t("padding_scheme", "Padding Scheme"),
          placeholder: t(
            "padding_scheme_placeholder",
            "One padding rule per line, format: stop=8, 0=30-30"
          ),
          group: "basic",
        },
        {
          name: "up_mbps",
          type: "number",
          label: t("up_mbps", "Upload Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "down_mbps",
          type: "number",
          label: t("down_mbps", "Download Bandwidth"),
          min: 1,
          placeholder: t(
            "bandwidth_placeholder",
            "Enter bandwidth, leave empty for BBR"
          ),
          suffix: "Mbps",
          group: "basic",
        },
        {
          name: "sni",
          type: "input",
          label: t("security_sni", "SNI"),
          group: "security",
        },
        {
          name: "allow_insecure",
          type: "switch",
          label: t("security_allow_insecure", "Allow Insecure"),
          group: "security",
        },
        {
          name: "fingerprint",
          type: "select",
          label: t("security_fingerprint", "Fingerprint"),
          options: FINGERPRINTS,
          defaultValue: "chrome",
          group: "security",
        },
        {
          name: "cert_mode",
          type: "select",
          label: t("cert_mode", "Certificate Mode"),
          options: CERT_MODES,
          defaultValue: "none",
          group: "security",
        },
        {
          name: "cert_dns_provider",
          type: "input",
          label: t("cert_dns_provider", "DNS Provider"),
          placeholder: "e.g. cloudflare, aliyun",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
        {
          name: "cert_dns_env",
          type: "textarea",
          label: t("cert_dns_env", "DNS Environment Variables"),
          placeholder:
            "CF_DNS_API_TOKEN=1234567890abcdefghijklmnopqrstuvwxyz\nALI_ACCESS_KEY_ID=your_access_key_id\nALI_ACCESS_KEY_SECRET=your_access_key_secret",
          group: "security",
          condition: (p) => p.cert_mode === "dns",
        },
      ],
    }),
    [t]
  );
}
